version: "3.6"

volumes:
  db_data:

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

  worker:
    # NOTE: to opt out of basic image pull tracking, comment out the current image
    # and uncomment the next line (which will pull from Docker Hub directly).
    # image: mergestat/worker:2.1.1-beta
    image: images.mergestat.com/mergestat/worker:2.1.1-beta
    privileged: true
    stop_grace_period: 10m
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/metrics"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_CONNECTION: postgres://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/postgres?sslmode=disable
      CONCURRENCY: 5
      GITHUB_RATE_LIMIT: 1/2
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET:-password}
      LOG_LEVEL: debug
      DEBUG: 1
      PRETTY_LOGS: 1
      GITHUB_WORKFLOW_PER_PAGE: 30
      GITHUB_WORKFLOW_RUNS_PER_PAGE: 30
      GITHUB_WORKFLOW_JOBS_PER_PAGE: 30
    ports:
      - 3301:8080

  graphql:
    # See NOTE above in worker service.
    # image: mergestat/graphql:2.1.1-beta
    image: images.mergestat.com/mergestat/graphql:2.1.1-beta
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      worker:
        # this is to ensure all migrations are run before the API starts up
        condition: service_healthy
    links:
      - worker
    ports:
      - 5433:5433
    command:
      - "--connection"
      - "postgres://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/postgres?sslmode=disable"
      - "--port"
      - "5433"
      - "--schema"
      - "mergestat,sqlq,public"
      - "--append-plugins"
      - "@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,/graphql/container-sync-jobs/index.js,/graphql/exec-sql/index.js,/graphql/service-credentials/index.js"
      - "-o"
      - "--subscriptions"
      - "--retry-on-init-fail"
      - "--dynamic-json"
      - "--no-setof-functions-contain-nulls"
      - "--no-ignore-rbac"
      - "--extended-errors=errcode"
      - "--disable-graphiql"
      - "--enable-query-batching"
      - "--disable-query-log"
      - "--legacy-relations=omit"
      - "--jwt-secret=${JWT_SECRET:-secret}"
      - "--default-role=mergestat_admin"
    environment:
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET:-password}
      DISPLAY_PG_HOSTNAME: localhost
      DISPLAY_PG_PORT: 5432
      DISPLAY_PG_DATABASE: postgres
      DISPLAY_PG_USER: postgres