services:
  postgres:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    expose: 
      - '5432'
    ports: # expose port to host machine in case we want to use external db gui tools
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

volumes:
  database:/pgdata