{
 "title": "Issues",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repositories",
    "label": "Repositories",
    "query": "SELECT owner || '/' || name FROM github_repo_info JOIN repos ON github_repo_info.repo_id = repos.id"
   },
   {
    "name": "repository_tags",
    "label": "Repository Tags",
    "query": "SELECT DISTINCT value FROM repos, jsonb_array_elements_text(tags) "
   },
   { "name": "interval", "label": "Interval", "query": "1d,7d,14d,30d,90d,180d" },
   {
    "name": "state",
    "label": "States",
    "query": "SELECT DISTINCT state FROM public.github_issues"
   },
   {
    "name": "labels",
    "label": "Labels",
    "query": "SELECT DISTINCT JSONB_ARRAY_ELEMENTS_TEXT(public.github_issues.labels) AS label FROM public.github_issues order by 1"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Issues by Creation Date by Repo (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_issues,\n    public.repos.repo,\n    $__timeGroup(public.github_issues.created_at, '${interval}', 0) AS time\nFROM public.github_issues\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE public.github_issues.closed = false\nAND $__timeFilter(public.github_issues.created_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Closed Issues by Closed Date by Repo (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_issues,\n    public.repos.repo,\n    $__timeGroup(public.github_issues.closed_at, '${interval}', 0) AS time\nFROM public.github_issues\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE public.github_issues.closed\nAND $__timeFilter(public.github_issues.closed_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Issues Created by Repo (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) AS total_issues,\n    public.repos.repo,\n    $__timeGroup(public.github_issues.created_at, '${interval}', 0) AS time\nFROM public.github_issues\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE public.github_issues.created_at IS NOT NULL\nAND $__timeFilter(public.github_issues.created_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  {
   "title": "Issues Created Labels (by ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH labels AS (SELECT\n        public.github_issues.database_id,\n        public.github_issues.repo_id,\n        JSONB_ARRAY_ELEMENTS_TEXT(public.github_issues.labels) AS label\n    FROM public.github_issues\n)\n\nSELECT\n    COUNT(*) AS total_issues,\n    labels.label,\n    $__timeGroup(public.github_issues.created_at, '${interval}', 0) AS time\nFROM public.github_issues\nINNER JOIN labels ON public.github_issues.repo_id = labels.repo_id AND public.github_issues.database_id = labels.database_id\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nWHERE public.github_issues.created_at IS NOT NULL\nAND $__timeFilter(public.github_issues.created_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nGROUP BY 2,3\nORDER BY 3"
    }
   ]
  },
  { "title": "Time To Close", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Mean Time To Close by Repo (per ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(EXTRACT(EPOCH FROM public.github_issues.closed_at - public.github_issues.created_at)) AS time_to_close,\n  $__timeGroup(public.github_issues.closed_at, '${interval}', 0) AS time,\n\t(public.github_repo_info.owner || '/' || public.github_repo_info.name) AS base_repository_name\nFROM github_issues\nINNER JOIN public.github_repo_info ON public.github_issues.repo_id = public.github_repo_info.repo_id\nINNER JOIN public.repos ON public.github_repo_info.repo_id = public.repos.id\nAND $__timeFilter(public.github_issues.created_at) \nAND (CASE WHEN jsonb_array_length('${repositories:json}'::jsonb) <> 0 THEN ('${repositories:json}'::jsonb ? (public.github_repo_info.owner || '/' || public.github_repo_info.name)) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${repository_tags:json}'::jsonb) <> 0 THEN (public.repos.tags @> '${repository_tags:json}'::jsonb) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${state:json}'::jsonb) <> 0 THEN ('${state:json}'::jsonb ? public.github_issues.state) ELSE true END)\nAND (CASE WHEN jsonb_array_length('${labels:json}'::jsonb) <> 0 THEN (public.github_issues.labels @> '${labels:json}'::jsonb) ELSE true END)\nWHERE github_issues.closed_at IS NOT NULL\nGROUP BY 2,3\nORDER BY 2"
    }
   ]
  }
 ]
}